services:
  backend:
    container_name: shopapi-backend
    build: ./backend/.
    ports:
      - "8000:8000"

  frontend:
    container_name: shopapi-frontend
    build: ./frontend/.
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  kuma:
    container_name: shopapi-monitoring
    image: louislam/uptime-kuma:latest
    ports:
      - "9000:3001"
    volumes:
      - uptime-kuma:/app/data
    restart: always

volumes:
  uptime-kuma:
